#include <stdio.h>
#include <stdarg.h>
#include <sys/types.h>
#include <unistd.h>
#include "../include/helpers.h"

int TRACE_MODE = 0;
static int USE_COLOR = 0;


/**
 * helpers_init()
 * Sets up the global state for the helper module.
 * Checks if the output is a terminal and respects the NO_COLOR standard.
 */
void helpers_init() {
    // Disable if NO_COLOR is set, otherwise check if it's a TTY
    if (getenv("NO_COLOR") != NULL) {
        USE_COLOR = 0;
    } else {
        USE_COLOR = isatty(STDERR_FILENO);
    }
}

/**
 * print_banner()
 * Displays the TRaSH ASCII logo with terminal-themed colors.
 */
void print_banner() {
    // ANSI Colors
    char *CYAN   = "\033[1;36m";
    char *BLUE   = "\033[1;34m";
    char *GRAY   = "\033[1;30m";
    char *RESET  = "\033[0m";

    printf("%s  _______  ______    _______  _______  __   __ \n", CYAN);
    printf(" |       ||    _ |  |   _   ||       ||  | |  |\n");
    printf(" |_     _||   | ||  |  |_|  ||  _____||  |_|  |\n");
    printf("%s   |   |  |   |_||_ |       || |_____ |       |\n", BLUE);
    printf("   |   |  |    __  ||       ||_____  ||       |\n");
    printf("   |   |  |   |  | ||   _   | _____| ||   _   |\n");
    printf("   |___|  |___|  |_||__| |__||_______||__| |__|\n");
    printf("%s    [ %sThe Shell That Explains Itself%s ]\n\n", GRAY, RESET, GRAY);
    printf("%s", RESET);
}

/**
 * trace_print()
 * Standard debug message. Useful for syscalls and flow control.
 */
void trace_print(const char *format, ...) {
    if (!TRACE_MODE) return;

    char *GREEN = USE_COLOR ? "\033[0;32m" : "";
    char *RESET = USE_COLOR ? "\033[0m"    : "";

    va_list args;
    va_start(args, format);

    fprintf(stderr, "%s[TRACE]%s ", GREEN, RESET);
    vfprintf(stderr, format, args);
    fprintf(stderr, "\n");

    va_end(args);
}

/**
 * trace_hex_buffer()
 * Prints a raw buffer in hex. Essential for debugging redirection and pipes.
 */
void trace_hex_buffer(const char *buf, ssize_t len) {
    if (!TRACE_MODE) return;

    char *MAGENTA = USE_COLOR ? "\033[0;35m" : "";
    char *RESET   = USE_COLOR ? "\033[0m"    : "";

    fprintf(stderr, "%s[TRACE HEX]%s ", MAGENTA, RESET);
    for (int i = 0; i < len; i++) {
        fprintf(stderr, "%02x ", (unsigned char)buf[i]);
    }
    fprintf(stderr, "\n");
}

/**
 * trace_tokens()
 * Prints the array of tokens generated by the parser.
 */
void trace_tokens(char **tokens, ssize_t token_count) {
    if (!TRACE_MODE || !tokens) return;
    
    char *YELLOW = USE_COLOR ? "\033[0;33m" : "";
    char *RESET  = USE_COLOR ? "\033[0m"    : "";

    fprintf(stderr, "%s[TRACE TOKENS]%s ", YELLOW, RESET);
    for (int i = 0; i < token_count; i++) {
        fprintf(stderr, "[%s]%s", tokens[i], (i == token_count - 1) ? "" : ", ");
    }
    fprintf(stderr, "\n");
}
